### ISSUE TITLE
[BUG] cannot instantiate `macros`

### ISSUE THREAD

**Issue by miloth** [KMKfw/kmk_firmware#1019]
**Describe the bug**
`TypeError` when using the `macros` module.

**To Reproduce**
Simply follow the example for the [macros](https://github.com/KMKfw/kmk_firmware/blob/main/docs/en/macros.md) module:
```python
from kmk.kmk_keyboard import KMKKeyboard
from kmk.keys import KC
from kmk.modules.macros import Macros

keyboard = KMKKeyboard()
keyboard.modules.append(Macros())

GIVE_ME_THE_ANSWER = KC.MACRO("fortytwo")
```

**Expected behavior**
The last command should instantiate the macro, to be assigned to one of the keys in the keyboard mapping.

**Debug output**
I get this error:
```
104984 kmk.keys: Invalid key: MACRO
Traceback (most recent call last):
  File "code.py", line 19, in <module>
TypeError: 'Key' object is not callable
```

**Additional context**
N/A.

**Comment by claycooper** [comment]
Can you post your whole `code.py` over at https://kmkfw.zulipchat.com/?

**Comment by BOBO-dingdang** [comment]
You need to do this:
macros = Macros()
keyboard.modules.append(macros)
