### ISSUE TITLE
No input sent to OS (presumably main.py frozen) until REPL is opened in CircuitPython 4.0-alpha.3+

### ISSUE THREAD

**Issue by klardotsh** [KMKfw/kmk_firmware#104]
@kdb424 ran into something similar and rolled WAY back (to like 3.x or something) when building out split keyboard support, but it's now come to a head when trying to put my Iris together tonight.

On CircuitPython 4.0.0-alpha.2, the keyboard works as expected, fully unattended. On all CircuitPython releases from 4.0.0-alpha.3 onwards (including the latest, alpha.5), the keyboard will send no data at all to the OS (presumably `main.py` is hung somewhere?) until the CircuitPython REPL is connected to in userspace (picocom or whatever).

The knock-on effect of this is that split keyboards are *completely nonfunctional* on these CircuitPython releases, as data is ALSO not sent across to the primary half of the keyboard.

I have only personally tested this on a split configuration with ItsyBitsy M4 Expresses converted to Pro Micro pinouts using the kitsym4 board. I have not upgraded my Planck/Klaranck past alpha2 as of yet, so I can't speak to whether single-piece keyboards and/or the Feather M4 Express are affected, but it's logical to assume that if single-piece keyboards are, the bug will affect that keyboard as well (I doubt the tiny differences between the IBM4 and FM4E are the smoking gun here).

This is effectively "critical priority", or whatever our equivalent of such is.

It is important, also, to note that breaking UART changes came in alpha5, so some reworking may be required while targeting these new releases.

**Comment by kdb424** [comment]
This seems to be a known upstream issue as downloads for alpha3 have been removed.
