### ISSUE TITLE
[Enhancement] Split key codes up from shift pairs

### ISSUE THREAD

**Issue by dowling-john** [KMKfw/kmk_firmware#1041]
**Is your feature request related to a problem? Please describe.**
It would be good to be able to split keys from their shift pairs

**Describe the solution you'd like**
For instance 9 and ( should be assignable to seperate keys

**Comment by xs5871** [comment]
You can already do that, so I'm assuming you actually want #409.

**Comment by dowling-john** [comment]
Thanks for the reply.

I am currently using a macro to define a single key press to get the ( symbol from a single key press.

```
LBRACK = MACRO(
   Press(KC.LSHFT)
   Tap(KC.N9) 
   Release(KC.LSHFT)
)
```

Is this the right way to tackle this problem or is there something that I have missed ?

**Comment by xs5871** [comment]
https://github.com/KMKfw/kmk_firmware/blob/main/docs/en/keycodes.md#us-ansi-shifted-symbols

**Comment by dowling-john** [comment]
How in the heck did I miss that 🤯 

Thanks
