### ISSUE TITLE
Tech Debt hitlist

### ISSUE THREAD

**Issue by klardotsh** [KMKfw/kmk_firmware#107]
This is a probably-ever-expanding catch-all ticket for tech debt that should be cleaned out for v1

- [ ] Remove `kmk/pins.py` entirely - this was a leftover from days of supporting MicroPython targets under a unified KMK-side API. It's gnarly, does too much, and will probably not do what the user expects if they try to use it as a generic GPIO pin in a macro.

- [ ] Clean up `ModifierKey` implementation? I dunno. It feels smelly.

- [ ] Is `kmktime` even worth keeping? Investigate what, if any, of this file is necessary in its current form vs. just importing `time` directly. Again, this file is mostly vestigial from MicroPython days

**Comment by kdb424** [comment]
kmktime needs removed. Nothing of use can't be converted if it's even called any more.

**Comment by kdb424** [comment]
Until the massive refactor, I believe that this was all resolved?
