### ISSUE TITLE
Leader key timeout still affects Enter Mode?

### ISSUE THREAD

**Issue by kdb424** [KMKfw/kmk_firmware#123]
I am timing out in enter mode seemingly, which seems to defeat the purpose. Maybe this is a feature? If so, there should be a higher default timeout when setting it.

**Comment by klardotsh** [comment]
Timeouts are definitely not a feature of Leader Mode Enter. I'll see if I can address.

**Comment by klardotsh** [comment]
I can't replicate this on my Iris (though I have other leader mode issues that I'm not sure whether are firmware-wide or board-specific... that's a different story entirely, though)
