### ISSUE TITLE
Rapid key presses may in some scenarios lead to dropped key presses

### ISSUE THREAD

**Issue by rk463345** [KMKfw/kmk_firmware#130]
In some gaming situations I have experienced dropped key presses when having to press multiple keys rapidly.

**Comment by klardotsh** [comment]
Can you give some details on:

- commit you're basing off of (whether that's our tree or your fork)
- MCU powering your board
- split? non-split?
- whether it's a standard letter key, modifier, or macro that's triggering oddly?

**Comment by kdb424** [comment]
Circuitpython has gotten a lot more performance since this issue has been posted which even smoothed animations on controllers that had previously struggled. Please test this again and re-open if it continues to be an issue.
