### ISSUE TITLE
Tapdance no longer works.

### ISSUE THREAD

**Issue by kdb424** [KMKfw/kmk_firmware#150]
```
Traceback (most recent call last):
  File "main.py", line 73, in <module>
  File "kmk/kmk_keyboard.py", line 300, in go
  File "kmk/kmk_keyboard.py", line 146, in _handle_matrix_report
  File "kmk/internal_state.py", line 130, in matrix_changed
  File "kmk/internal_state.py", line 139, in process_key
  File "kmk/keys.py", line 84, in _on_release
  File "kmk/handlers/stock.py", line 134, in td_released
  File "kmk/internal_state.py", line 194, in _process_tap_dance
AttributeError: 'Key' object has no attribute 'codes'

HELLA_TD = KC.TD(
    KC.A,
    KC.B,
    send_string('macros in a tap dance? I think yes'),
    KC.TG(1),
)
```

**Comment by kdb424** [comment]
We need to see if this is even still a problem.

**Comment by pullenrc** [comment]
This just happened to me, I'm not sure if I should have posted here first, at any rate I didn't see this until after the new issue was open.

**Comment by klardotsh** [comment]
Reopening; closing #202 as dupe

**Comment by klardotsh** [comment]
I need to get an actual KMK dev board back up to test this - I basically have my production board that hasn't been touched in years, and... somewhere in the pile of maker hardware are the MCUs and breadboards I used to test features on :)

Doing some heavy electrical and plumbing lifts on my sailboat this weekend so can't promise I'll have time to look into this before, say, mid week, but I'll try to at least get a repro so I can figure out what's going on.

If you haven't already, see if you can spin anything up on the "new master" branch, https://github.com/KMKfw/kmk_firmware/tree/topic-merge-keyboard-and-state-rebased. That's something like 95% complete and works on non-split boards (the discussion about what it'll take to get that across the finish line has been ongoing on the Matrix/Discord chat, drop in there any time if you need more real time help!)

**Comment by pullenrc** [comment]
I will give the rebased branch a shot, sounds interesting.

**Comment by pullenrc** [comment]
On the rebased branch TD is still giving this error, exactly as above.  I'll dig around, however, I am still familiarizing myself with the new branch.

**Comment by xs5871** [comment]
I think this issue can be closed.

**Comment by kdb424** [comment]
It should have auto closed if tagged. Thanks for the heads up!
