### ISSUE TITLE
Add debounce

### ISSUE THREAD

**Issue by kdb424** [KMKfw/kmk_firmware#188]
Debounce needs added as an option. Example in python and C is here https://learn.adafruit.com/extending-circuitpython/a-complex-module and this will help with some switches that have issues with "imperfect signals" sent from them. I recently installed some Holy Pandas, and these are showing a need for debouncing. This should be configured be default at a global level of 5ms vs the listed 10ms in the example, but have the ability to override by board/user level.

**Comment by klardotsh** [comment]
Superceded by #237
