### ISSUE TITLE
Add vim combos

### ISSUE THREAD

**Issue by kdb424** [KMKfw/kmk_firmware#190]
https://beta.docs.qmk.fm/using-qmk/software-features/feature_combo 
This is the given example for the feature that was requested.

**Comment by xs5871** [comment]
Update: we have basic support for combos, but there's still some way to go to get the full flexibility of QMK combos.
still missing (terminology from the QMK docs):
- [ ] COMBO_MUST_HOLD_PER_COMBO
- [ ] COMBO_MUST_TAP_PER_COMBO
- [ ] COMBO_SHOULD_TRIGGER
- [ ] COMBO_NO_TIMER
- [ ] layer allow/block list

**Comment by kdb424** [comment]
I'm unlikely to ever bother to do this, and no one else has interest. Closing
