### ISSUE TITLE
Matrix and Discord invites don't work

### ISSUE THREAD

**Issue by AndreEagleDolla** [KMKfw/kmk_firmware#197]
I am trying to join the matrix/discord server but the discord invite is expired and the matrix rooms all say:

"#kmk-support:kmkfw.io is not accessible at this time. Try again later, or ask a room admin to check if you have access."

**Comment by klardotsh** [comment]
You're not the first person to mention getting sent to the old `kmkfw.io` homeserver but I can't for the life of me figure out where this link is - do you happen to remember what sent you there? From what I can tell the current `master` README has working links for both Matrix and Discord

**Comment by AndreEagleDolla** [comment]
Absolutely! I found it under docs > support https://github.com/KMKfw/kmk_firmware/blob/master/docs/support.md

**Comment by klardotsh** [comment]
Thanks! Fixed in `master`
