### ISSUE TITLE
Unable to load hardware/itsy_bitsy_to_pro_micro into Eagle or KiCAD

### ISSUE THREAD

**Issue by rabbit-88** [KMKfw/kmk_firmware#201]
It appears the schematic and pcb layout for "itsy_bitsy_to_pro_micro" (under Hardware) was created with Eagle, but the current of Eagle is unable to load either file, and KiCAD is also unable to import either file.  

Looking to create something similar between the ProMicro footprint and the Raspberry Pi PICO footprint.

Would be grateful for any clues how to load this into KiCAD 5.10 or KiCAD 5.99.

**Comment by Gigahawk** [comment]
Seems to work fine in EAGLE for me:

![image](https://user-images.githubusercontent.com/10356230/133385442-2bf42102-db13-455b-896a-767365cf4a8b.png)

KiCad import also seems to work fine for me:
![image](https://user-images.githubusercontent.com/10356230/133385805-9ff25b50-1f77-4dba-a42a-545ed2baa82e.png)
