### ISSUE TITLE
use supervisor.ticks_ms if available

### ISSUE THREAD

**Issue by jepler** [KMKfw/kmk_firmware#215]
CircuitPython adds [`supervisor.ticks_ms()`](https://circuitpython.readthedocs.io/en/latest/shared-bindings/supervisor/index.html#supervisor.ticks_ms) as a wrapping time source.  It would be nice if kmk used this in lieu of its own ticks_ms, but the substitution isn't 1:1 because `supervisor.ticks_ms()` wraps every 2**29ms (but it never loses precision).  There are routines suggested in the docs for comparing tick values and adding durations to tick values (to implement deadlines/timeouts); these will someday (soon?) be packaged into a new `adafruit_ticks` library (with compatibility code for 6.3) so it may also make sense to wait for that to pop up.

**Comment by kdb424** [comment]
@jepler I have linked a PR to resolve this. Testing and any suggestions from you would be appreciated.
