### ISSUE TITLE
Investigate use of non-C languages for lowest-level functionality

### ISSUE THREAD

**Issue by klardotsh** [KMKfw/kmk_firmware#216]
This is more of a kmkfw/kmkpython issue, but since this board is the KMK overall issue tracker, I'm opening it here.

@kdb424 and I have discussed some functionality that would require work in CircuitPython/KMKPython land, that is probably too performance-sensitive to do in pure Python. Since neither of us are particular fans of C, some alternatives come to mind. It would be interesting to see how any of them could fit into MicroPython/CircuitPython's internals:

- [Zig](https://ziglang.org), which speaks C ABI and aims to be "the next C", if you will. It's similarly low level - fewer footguns (and far more compiler guarantees) than C, but still requires, for example, tracking memory allocations (indeed, while the standard library ships (de)allocators, you're in charge of managing them)
- [Nim](https://nim-lang.org/), almost certainly the most Pythonic-like option and a personal favorite of both of ours. While it compiles to C and [folks have bound simple Arduino functionality with it](https://disconnected.systems/blog/nim-on-adruino/), it does not natively speak the C ABI, has its own runtime, and has (optional) garbage collection, which means Nim CircuitPython modules would be speaking over some form of FFI to the rest of the VM. This may or may not matter for performance, but would be mental overhead to keep track of during development.
- [Nelua](https://nelua.io/) seems to strike a middle ground between the two: it's more or less Lua (with all of its readability and clean syntax and simple/elegant design), but compiling to C and speaking C ABI. I haven't played much with it beyond this level of understanding.

**Comment by kdb424** [comment]
Unlikely this is ever going to see effort by us, and very few would want to mix these other code types in here at this point. With extensions and moving to upstream libs where possible, closing for now.
