### ISSUE TITLE
forward slash not allowed

### ISSUE THREAD

**Issue by ydna8981** [KMKfw/kmk_firmware#220]
I am unable to add any forward slash to send_string, all other characters that I need are working fine except "/" i have tried with the regular escape sequence characters none of it helped. Can someone help me here or is this not possible?

**Comment by Max585t** [comment]
Ive run into the same bug, Im going to look into possible fixes

**Comment by Max585t** [comment]
@ydna8981 The fix is super easy, just change `make_key(code=56, names=('SLASH', 'SLSH'))` to `make_key(code=56, names=('SLASH', 'SLSH', '/'))`

**Comment by klardotsh** [comment]
This didn't auto-close due to a typo in the PR message, but https://github.com/KMKfw/kmk_firmware/pull/231 resolved this.
