### ISSUE TITLE
Add timeout/swallow API's

### ISSUE THREAD

**Issue by kdb424** [KMKfw/kmk_firmware#222]
There are many keys that are dual use such as tap dance, mod tap, layer tap, ect. We need an API to allow this to become a standard to allow creating keys that can swallow/absorb keystrokes, and process them on timeouts, or even discard them completely. This allows us to restore tapdance, and Leader Mode easily, as well as add new features easily, such as combos.

I have started thinking about this problem, and this is what I have so far. This is open for discussion as no actual code is written, only the pseudo code below.

```python
def swallow(keycode, swallow_timeout=100, suppression=True)
    # keycode: Any valid keycode
    # swallow_timeout: Timeout in ms
    # suppression: allows the action to pass through or not
    timeout(keycode, time_in_ms)
   

def evict(keycode=None, empty=False)
    # keycode: Any valid keycode
    # empty: If all keys stored should be evicted
def revert(keycodesStored, suppression=False):
    # keycodesStored: list of all keycodes that were, or were not suppressed
    if not suppression:
        # Keycodes will need to be backspaced as they were not suppressed
        pass
    else:
        # Keys were suppressed and not typed. Just evict queue
        evict(keycode=None, empty=True)
    
```

## Leader mode

```python
if kc:
    leaderStored.ammend(swallow(keycode=kc, swallow_timeout=0, suppression=True))

if match in leaderStored:
    # do the leader macro or whatever
    revert(keycodesStored=leaderStored, suppression=True)
    
```

## Combos
```python
if kc:
    comboStored.ammend(swallow(keycode=kc, swallow_timeout=0, suppression=False))

if match in comboStored:
    # do the leader macro or whatever
    revert(keycodesStored=comboStored, suppression=True)

elif timeoutReached:
    # pop the oldest key off of the stack and reset timer
    pass

```

# Timeout

Timouts should store an end "timestamp" as well as a keycode.
A callback timer will automatically evict the keycode when the timeout
is reached if it has not already been evicted.

A list of touples should be usable, though other ideas are welcome.
```python
timeout_callbacks = [(KC_NO, timeout_expires), (KC_ESC, timeout_expires)]

def create_timeout(keycode=None, time_in_ms):
    # keycode: any valid keycode
    # time_in_ms: how long to wait
    # returns: timeout(keycode, expires_at_time)
```

**Comment by xs5871** [comment]
would it help to extract the tap dance logic from `kmk_keyboard` and make it its own module?
