### ISSUE TITLE
Host OS detection

### ISSUE THREAD

**Issue by bill-ash** [KMKfw/kmk_firmware#250]
Just finished a hand wired board using a pico running circuitpython 7.0. 

I'm wondering if it is possible to detect the host os when plugged in via usb to change the default base key map depending on windows/Mac/Linux. 

I manually change the layer when switching from work to personal but it would be cool if this could be automated. 

Had a lot of fun building my keyboard. Super happy to have stumbled upon kmk!

**Comment by xs5871** [comment]
The only data transmitted from host to the keyboard is status information of lock keys (num, caps etc.).
You would have to implement your own host and device side drivers, or hijack the lock key status to tell the keyboard about your host system.
