### ISSUE TITLE
Mouse keys do not work on PICO

### ISSUE THREAD

**Issue by pcharest2000** [KMKfw/kmk_firmware#286]
KMK:  Latest pull from 05-12-2021
Circuit Python: 7.0
Hardware: Pi Pico

The mouse keys do not work at all, debug log:

KeyResolution(key=Key(code=1006, has_modifiers=None))
Failed to run pre hid function in module:  Buffer incorrect size. Should be 8 bytes. <MouseKeys object >
KMKKeyboard(debug_enabled=True diode_orientation=0 matrix_scanner=<class 'MatrixScanner'> unicode_mode=)
Failed to run pre hid function in module:  Buffer incorrect size. Should be 8 bytes. <MouseKeys object >
Failed to run pre hid function in module:  Buffer incorrect size. Should be 8 bytes. <MouseKeys object >

Does not seem to be a Circuit Python issue since the following example works:
https://tutorial.cytron.io/2021/07/06/diy-usb-keyboard-mouse-using-maker-pi-pico/

**Comment by klardotsh** [comment]
should be fixed in master thanks to #289, feel free to reopen if it's still an issue
