### ISSUE TITLE
Attaching a callback on mod key

### ISSUE THREAD

**Issue by pcharest2000** [KMKfw/kmk_firmware#287]
Attaching a callback on a mod key does not seem to work:

KC.MO(1).before_press_handler(ledOn)

But attaching on a Modtap works  (a work around sending no other keys):
LT1=KC.LT(1,KC.NO)
LT1.before_press_handler(ledOn)

or...

LAYER1=KC.MO(1)
LAYER1.before_press_handler(ledOn)

**Comment by xs5871** [comment]
I can't reproduce this. Is this still an issue, and if so, could you be more specific or share your configuration?

**Comment by kdb424** [comment]
Closing as this is stale.
