### ISSUE TITLE
RGB working in non rgb boards.

### ISSUE THREAD

**Issue by roykos4114** [KMKfw/kmk_firmware#308]
i hand build a board i want to use rgb on i have them but i cant get the code to work on the KMK side.

**Comment by kdb424** [comment]
This would be a better discussion to have in the discord/matrix, or we will need some more information as there's not much I can do with this limited information.

**Comment by roykos4114** [comment]
Can you send a link to the sever
Please and thank you

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by kdb424** [comment]
It's in the main readme on the repo for both the matrix and discord side.

**Comment by roykos4114** [comment]
I have tried the likns they did not work. I have been trying to get this working for over 2 weeks the the adafruit discord sever CP help. With no luck


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by kdb424** [comment]
https://discord.gg/QBHUUpeGUd
