### ISSUE TITLE
Example for disableing CDC/storage HID in boot.py

### ISSUE THREAD

**Issue by xs5871** [KMKfw/kmk_firmware#339]
We should add an example for disableing CDC/storage HID in `boot.py` to the documentation, including setup for a boot mode key/switch.

**Comment by kdb424** [comment]
Would happily take a PR for some docs on this.

**Comment by justinesmithies** [comment]
I've just done this using my Pico TKL diode matrix to check for a particular key press at boot to enable maintenance mode and it works a treat. Happy to share my working example.
[boot.py](https://paste.sr.ht/~justinesmithies/c2013762698dd1560f6f11b9a10bddc893854a47)

**Comment by kdb424** [comment]
If you could write that up in some sort of a readme style thing with the "required changes", and open a pull request, we'll surely get that in.

**Comment by HBBisenieks** [comment]
I believe this has been solved by #359 and #361
