### ISSUE TITLE
Shift Register Scanner fails on Go.

### ISSUE THREAD

**Issue by scndthe2nd** [KMKfw/kmk_firmware#395]
Using the examples provided for Shift Register Scanner, the scanner fails, requesting 1 positional argument on 'go'. This argument is not requested with the keypad matrix or key scanner.

![image](https://user-images.githubusercontent.com/15825472/163440002-13a9a751-9efb-4463-9f42-7fade0f88c1c.png)

Tested on 2022/04/14 using latest build on kb2040 using 74HC597 PISO.
`
print("Starting")

import board

from kmk.kmk_keyboard import KMKKeyboard
from kmk.keys import KC
from kmk.scanners.keypad import ShiftRegisterKeys
import time
import neopixel

from kmk.scanners import DiodeOrientation
keyboard = KMKKeyboard()

class keyboard(KMKKeyboard):
    def __init__(self):
        # create and register the scanner
        self.matrix = ShiftRegisterKeys(
            # require arguments:
            clock=board.d5,
            data=board.d4,
            latch=board.d3,
            key_count=8,
            # optional arguments with defaults:
            value_to_latch=True, # 74HC165: True, CD4021: False
            value_when_pressed=False,
            interval=0.02,
            max_events=64
        )

keyboard.keymap = [
    ["SW0",  "SW1",  "SW2", "SW3",
    "SW4",  "SW5",  "SW6", "SW7"],
]

KMKKeyboard.debug_enabled = True

pixel = neopixel.NeoPixel(board.NEOPIXEL, 1)

pixel.brightness = 0.01

if __name__ == '__main__':
    keyboard.go()

while True:
    pixel.fill((0, 0, 0))
`

**Comment by xs5871** [comment]
There are a couple of errors in your configuration.
There's no positional argument to `go` because you didn't instanciate the keyboard object, but calling the method from the class definition. That's not the only issue in the code, though.
The matrix channel would be a good place to get help fixing your config first.

**Comment by kdb424** [comment]
Closing as I saw this was a keymap problem, and not a KMK problem, as well as being discussed in matrix/discord. Feel free to reopen if this is actually a KMK issue.
