### ISSUE TITLE
Online/rendered version of docs on readthedocs.org

### ISSUE THREAD

**Issue by stefanfoulis** [KMKfw/kmk_firmware#463]
Would it be desirable to have the docs nicely rendered and available somewhere online?
For example on https://readthedocs.org/

It is possible to set it up so that the docs are automatically built and updated on readthedocs whenever anything is added to the `master` branch.

Maybe related to #419 .

**Comment by stefanfoulis** [comment]
I could help setting this up.

**Comment by kdb424** [comment]
Kinda like this? http://kmkfw.io/docs/

**Comment by stefanfoulis** [comment]
haha, wow. Those docs are very nice.
I totally missed them :man_facepalming: .

It hasn't showed up on any of my google searches. Even when searching for `kmk docs`, `kmk keyboard docs` or `kmk firmware docs` (github is most prominent in the results).

So maybe we could change this issue to read `Link to docs from README.md` :man_shrugging:  :grin: .
