### ISSUE TITLE
tapdance reporting key in wrong order

### ISSUE THREAD

**Issue by crazyiop** [KMKfw/kmk_firmware#467]
When a TapDance key is pressed, it's timeout to see if it is pressed again can be interrupted by other keys. It's reaction to potential interrupt are not coherent depending on press/release sequence.

To reproduce:
```python
AB_TD = KC.TD(KC.A, KC.B, tap_time=1000)  # big tap_time make it easy to reproduce
keyboard.keymap = [[AB_TD, KC.C]]

if __name__ == '__main__':
    keyboard.go()
```

working ok:
press a (t=0), press c (t=100), release a (t=200), release c (t=300) -> output 'ac' at t=200

what is broken:
press a (t=0), release a (t=100), press c (t=200), release c (t=300) -> output 'c' at t=200, then 'a' at t=**1000**

what is expected in that case:
output 'ac' at t=200

Looks like the current key_pressed are looked to interrupt the timer, but it should be the presence of the timer itself.

I'll give a shot at resolving it myself...

**Comment by xs5871** [comment]
I've got it almost fixed. One of the complicating factors is, that noone wrote a unit test for tapdance yet.
