### ISSUE TITLE
Configuration for Kyria V2 with nice!nano

### ISSUE THREAD

**Issue by stefanfoulis** [KMKfw/kmk_firmware#478]
My work in progress is here: https://github.com/stefanfoulis/keyboard-config-kyria-kmk/blob/main/kyria_v2_nice_nano.py

It took me some time to figure out the pins and how the kyria v2 board is wired. (hint: it is not like the v1 and there are currently barely any docs available for v2/v2.1).

I'll make a proper PR once I've figured out the details and made it more generically useful.
In the meantime I hope the linked file above can help anyone trying to get this combination of microcontroller and keyboard to work in kmk.

**Comment by klardotsh** [comment]
Closing since this isn't an issue; it'll remain searchable and indexable by DuckDuckGo and the like.
