### ISSUE TITLE
Chord doesn't always respect timeout value

### ISSUE THREAD

**Issue by Jawfish** [KMKfw/kmk_firmware#528]
The chord feature of the combos module doesn't use a user-set timeout until that timeout has passed since the last keystroke.
Example:
```python
keyboard.modules = [
    combos,
]
combos.combos = [Chord((KC['1'], KC['2']), KC['3'], timeout=5000)]
keyboard.keymap = [KC['1'], KC['2'], KC['3'], KC['B']]
```
Typing 1 or 2 within the first 5000 milliseconds of the previous non-chord keypress will send 1 or 2 rather than waiting up to 5000ms for the next keypress. The chord still works if you press it within the default 50ms timeout. After 5000ms has passed since the last keystroke, it works as expected.

Current behavior:
1. B is pressed
2. B is released
3. The following occurs within 5000ms of B being released:
  a. 1 is pressed
  b. 1 is sent by the keyboard to the computer
  c. 2 is pressed
  d 2 is sent by the keyboard to the computer
  e. 2 is released
  f. 1 is released
11. 5000ms passes
12. The following occurs within 5000ms
  a. 1 is pressed
  b. 2 is pressed
  c. 3 is sent by the keyboard to the computer

Expected behavior:
1. B is pressed
2. B is released
3. The following occurs within 5000ms of B being released:
  a. 1 is pressed
  b. 2 is pressed
  c. 3 is sent by the keyboard to the computer

**Comment by xs5871** [comment]
That's "intentional". You pressed B+1+2 within the combo timeout, and that key combination doesn't match the chord 1+2.
Is what you expect a rolling matching window?

**Comment by Jawfish** [comment]
B is released before 1 is pressed in my example.

**Comment by Jawfish** [comment]
I updated my comment to make it more clear, previously I just said 'tap' to mean a press-and-release action.

**Comment by Jawfish** [comment]
Here's a test I wrote for this that fails:

```python
# the config
combos.combos = [
    Chord((KC.F, KC.G), KC.Z),
]
self.keyboard = KeyboardTest(
    [combos, layers],
    [
        [KC.A, KC.B, KC.C, KC.D, KC.E, KCMO, KC.F, KC.G],
        [KC.N1, KC.N2, KC.N3, KC.N4, KC.N5, KC.LEADER],
    ],
)

# the test
keyboard.test(
    'match: Other pressed before combo',
    [
        (1, True),
        (1, False),
        (7, True),
        (6, True),
        (6, False),
        (7, False),
        t_after,
    ],
    [{KC.B}, {}, {KC.Z}, {}],
)
```
The failure:
```python
assert mods: 0 == 0 keys: {'B'} == {'B'} 
assert mods: 0 == 0 keys: set() == set() 
assert mods: 0 == 0 keys: {'G'} == {'Z'} 
assert mods: 0 == 0 keys: {'F', 'G'} == set() 
assert mods: 0 == None keys: {'G'} == {None} 
assert mods: 0 == None keys: set() == {None} 
```
Remove the `KC.B` press and it passes. I'll look into the code tomorrow if I have time.
