### ISSUE TITLE
PR 9d55520 breaks layer tap and reboots my board

### ISSUE THREAD

**Issue by justinesmithies** [KMKfw/kmk_firmware#566]
Just updated to the latest Git and now when I hold my layer key and release it reboots the board.
I have found that this PR 9d55520 is the issue and regressed to the previous PR and all is fine.

This is the line for my layers that i use `LAYER1 = KC.LT(1, KC.APPLICATION)`
I'm running on the latest circuit python release on my RP2040.

**Comment by kdb424** [comment]
We found this was a pystack exhaustion. Later commits, probably from #537 may have had a decent impact on memory size. This may need investigated.

**Comment by xs5871** [comment]
I've found a working fix, not particularly pretty, but it's not passing the unit tests yet.
