### ISSUE TITLE
Can kmk firmware build as ".uf2" file?

### ISSUE THREAD

**Issue by gezhaoyou** [KMKfw/kmk_firmware#572]
Can kmk firmware build as ".uf2" file? I  don't want user see "CIRCUITPY" disk.

**Comment by klardotsh** [comment]
Long, long ago we did ship U2Fs via a forked CircuitPython as the default implementation. It's not coming back in that form here in this repo (though forks are welcome to do whatever they want, this is a GPL project).

These days you can disable the `CIRCUITPY` disk [using `boot.py`](https://learn.adafruit.com/customizing-usb-devices-in-circuitpython/circuitpy-midi-serial#circuitpy-mass-storage-device-3096583)
