### ISSUE TITLE
keyboard does not work on startup

### ISSUE THREAD

**Issue by Melunis** [KMKfw/kmk_firmware#601]
looking for help using rpi pico, keyboard does not work on startup, need to restart board or unplug and plug it back in

**Comment by kdb424** [comment]
Can we get logs or anything that can be used to help debug this? That's not how things should work.

**Comment by klardotsh** [comment]
This issue needs repro steps or is inactionable and should be closed.

Free-form support fits the Matrix channel, but not GH Issues unless repro steps are provided and able to help isolate a potential issue in the codebase.
