### ISSUE TITLE
Need help with test for main.py changes

### ISSUE THREAD

**Issue by TellNoLies** [KMKfw/kmk_firmware#614]
Hello,
I am trying to change the keyboard layout for the lily58 on the nice_nano v1.
I keep getting "./boards/lily58/main.py:41:85: E999 SyntaxError: invalid syntax"
With the lack of experience, I have no clue what it is that I need to fix.
link to my main.py "https://github.com/TellNoLies/kmk_firmware/blob/master/boards/lily58/main.py"
I would really appreciate the help.

Thank you for your time.

**Comment by xs5871** [comment]
That's really not what the issue tracker of the project is for.
Quoting the `README.md`:

> If you need support with KMK or just want to say hi, find us in [#kmkfw:klar.sh on Matrix](https://matrix.to/#/#kmkfw:klar.sh).
> This channel is bridged to Discord [here](https://discord.gg/QBHUUpeGUd) for convenience.
