### ISSUE TITLE
Qwerty to azerty

### ISSUE THREAD

**Issue by YoanDev** [KMKfw/kmk_firmware#641]
Hi, I search how to convert my keyboard qwerty to a azerty keyboard.

I found this link :
https://github.com/KMKfw/kmk_firmware/blob/master/docs/en/keycodes.md

But I don't know how use International Keys to success.

Thanks

**Comment by xs5871** [comment]
International keys don't let you use an azerty layout instead of qwerty.
Someone started a PR (#431) to support azerty, but they never finished it.

**Comment by YoanDev** [comment]
Thanks, I found the work of crazyiop. I will test his code tomorrow.
