### ISSUE TITLE
Pimoroni Trackball starts as clicked upon connection

### ISSUE THREAD

**Issue by slabua** [KMKfw/kmk_firmware#649]
I've been having an issue with the trackball. Whenever I connect the keyboard to the pc, the trackball starts in the clicked status. Once I click on it it gets released and I can start using the keyboard normally.
Has anyone encountered the same problem?

**Comment by xs5871** [comment]
No, but the pointing device HID handling is due for a refactor anyway, see #625.

**Comment by slabua** [comment]
@xs5871 thank you! I will keep my source up to date and see what happens.
