### ISSUE TITLE
Change entrypoints to keyboards

### ISSUE THREAD

**Issue by kdb424** [KMKfw/kmk_firmware#67]
To add keyboard definition support and clear up confusion, make the current "handwire" folder into mcu as that should point to a microcontroller. This would be a lot clearer terminology, and allow us to have pre-built keyboard definitions, and even common hand wire setups be defined, allowing users to build keyboards much easier, not having to understand "what goes on", just "that it is this keyboard", along with making defining a PCB much easier.

**Comment by klardotsh** [comment]
I'm going to take this as part of the omega-PR spawning out of #70
