### ISSUE TITLE
Matrix link in repo description

### ISSUE THREAD

**Issue by claycooper** [KMKfw/kmk_firmware#678]
The link to Matrix is still in the repo's description. It should probably be changed to link to Zulip instead.

**Comment by CupricReki** [comment]
It's also still in the 'about' section

**Comment by claycooper** [comment]
![image](https://user-images.githubusercontent.com/3612906/214376778-3eb1f571-2f5b-4710-891f-2f2a620303a8.png)

There's a reference on the right side of the top-level repo view. If you have permissions on the repo there's a gear that shows on the top-right of that panel where you can change it to https://kmkfw.zulipchat.com/

**Comment by xs5871** [comment]
I would never have noticed that... thanks.
Technically that should point to a project website, maybe it did point to the rendered docs before they got out of sync. Anyway, I set it to zulip for now.
