### ISSUE TITLE
Nordic nRF52840 compatibility

### ISSUE THREAD

**Issue by Galvo87** [KMKfw/kmk_firmware#679]
Hi, is KMK compatible with [Nordic nRF52840 BT chips like this one?](https://www.aliexpress.com/item/32868365660.html?spm=a2g0o.order_list.order_list_main.5.1a271802KuMKjz)
Thanks

**Comment by xs5871** [comment]
Does Ciruitpython support it?

**Comment by Galvo87** [comment]
> Does Ciruitpython support it?

I think it's not officially supported.

**Comment by xs5871** [comment]
I see you posted that question also [on our support chat](https://kmkfw.zulipchat.com/#narrow/stream/358347-general/topic/nRF52840.20Support), with more valuable feedback.
Can we close this issue?

**Comment by Galvo87** [comment]
Sure. I will try to port CP onto the newest Nordic chip.
Thanks.
