### ISSUE TITLE
Unable to make an encoder working

### ISSUE THREAD

**Issue by Pip0une** [KMKfw/kmk_firmware#680]
I am unable to make an encoder working on my custom macro pad.

The macro pad is used for media control and the encoder to control volume.
The keys are working fine. With picocom i am able to see the debugg information and there is not much to say.

if i take the exemple for encoder, this code below should work.

The code :

`print("Starting")

import board

from kmk.kmk_keyboard import KMKKeyboard
from kmk.keys import KC
from kmk.scanners import DiodeOrientation
from kmk.extensions.media_keys import MediaKeys
from kmk.modules.encoder import EncoderHandler

keyboard = KMKKeyboard()
encoder_handler = EncoderHandler()
keyboard.modules = [encoder_handler]
keyboard.debug_enabled = True

keyboard.col_pins = (board.GP16, board.GP20, board.GP22, board.GP28)
keyboard.row_pins = (board.GP14, )
keyboard.diode_orientation = DiodeOrientation.COL2ROW

keyboard.extensions.append(MediaKeys())

encoder_handler.pins = (board.GP8, board.GP12, None, False)# whenever I put a comma here i have this error repeating itself undefinitly : kmk.kmk_keyboard: Error in <EncoderHandler object at 0x20008cd0>.before_matrix_scan: 'ConsumerKey' object isn't subscriptable

keyboard.keymap = [
    [KC.AUDIO_MUTE, KC.MEDIA_PREV_TRACK, KC.MEDIA_PLAY_PAUSE, KC.MEDIA_NEXT_TRACK]
]

encoder_handler.map = [(KC.VOLD, KC.VOLU, KC.NO)
]

if __name__ == '__main__':
    keyboard.go()
`
The startup message : 

`Starting
633752 kmk.keys: NO: Key(code=1000, has_modifiers=None)
633755 kmk.kmk_keyboard: Initialising default matrix scanner.
'Pin' object isn't subscriptable
'Pin' object isn't subscriptable
'NoneType' object isn't subscriptable
'bool' object isn't subscriptable
633777 kmk.kmk_keyboard: init: KMKKeyboard(
  debug_enabled=True, diode_orientation=0, matrix=(<MatrixScanner object at 0x2000a6d0>,),
  unicode_mode=0, _hid_helper=USBHID(REPORT_BYTES=9),
  keys_pressed=set(),
  _coordkeys_pressed={},
  hid_pending=False, active_layers=[0], _timeouts={}
)
`

**Comment by xs5871** [comment]
This doesn't merit a project issue. You already posted your problem in the official support platform and it's clearly a user/configuration problem, not an issue with the firmware.
