### ISSUE TITLE
Implement at least basic tests of the InternalState

### ISSUE THREAD

**Issue by klardotsh** [KMKfw/kmk_firmware#71]
It should be reasonable to implement a shim/patch `firmware` object which manually injects various matrix scans into the "reducer" (that will be going away with #70 but the ideas will generally stand), and validate the state afterwards. This will let us ensure there are no regressions going forward (and actually give us something useful to run on Circle now that we're not stuck validating patched CircuitPython builds)

**Comment by xs5871** [comment]
We have unittests now. Those sound exactly like what you're describing.
