### ISSUE TITLE
Deprecate ModTap in favor of HoldTap

### ISSUE THREAD

**Issue by xs5871** [KMKfw/kmk_firmware#717]
The `ModTap` module has been a historic alias for `HoldTap`. The former name is misleading, because the functionality isn't restricted to modifiers -- the name should reflect that universality.
We should go through docs, boards, and keymaps and replace every occurance of `ModTap` module/keys  with the equivalent `HoldTap` version.

**Comment by Vanphongle** [comment]
Hi, do you mean replacing all of ModTap with HoldTap and modtap with holdtap?

**Comment by xs5871** [comment]
Yes, and `KC.MT` with `KC.HT`.

**Comment by Vanphongle** [comment]
I just created a pull request. Please review the changes
