### ISSUE TITLE
Broke my code.py file

### ISSUE THREAD

**Issue by wdevore** [KMKfw/kmk_firmware#732]
Hi I was messing with the parameters on my Anavi - 10.

I added the line:
```
    brightness=10,
```
to the underglow RGB section and now it won't connect and show the CIRCUITPY device. I realized that was not a correct parameter.
How do I copy the correct **code.py** back to the Anavi?

Thanks.

**Comment by xs5871** [comment]
We do user support on our excellent [Zulip chat](https://kmkfw.zulipchat.com/). Github issues are reserved for firmware related topics.

With the limited information you provide, it doesn't look like it should have bricked your board and stop it from mounting as a USB device. Needs further discussion, please join refere to the chat :)
