### ISSUE TITLE
[BUG] Link for sequences on the documentation page are dead

### ISSUE THREAD

**Issue by gistogisto** [KMKfw/kmk_firmware#765]
**Describe the bug**
 Link for sequences on the documentation page are dead :
 on http://kmkfw.io/docs/keycodes , a link called SEQUENCES don't work

**To Reproduce**
-Go to http://kmkfw.io/docs/keycodes
- Search for the term SEQUENCES on the page
- Click on it

**Expected behavior**
The documentation of SEQUENCES appear

**Debug output**

**Additional context**
![Untitled 5](https://user-images.githubusercontent.com/10177102/233838289-561cfdab-3c86-496e-87a4-fc3879c63e6d.png)

**Comment by gruvw** [comment]
Same applies for link to http://kmkfw.io/docs/en/flashing.md in http://kmkfw.io/docs/config_and_keymap ("our Makefile") which should point to http://kmkfw.io/docs/flashing/

I think there is a pattern where every link pointing to `/docs/*.md` is broken (and should point to `/docs/*/`).

For some reason, first level links pointing to `*.md` are not broken.
