### ISSUE TITLE
RFC: Change jurisdiction of contributor CLA from BC to WA

### ISSUE THREAD

**Issue by klardotsh** [KMKfw/kmk_firmware#78]
This seems like an entirely logical change now that I look that document over again and realize I used my current resident jurisdiction rather than my "legally a citizen of" jurisdiction in the docs. Whoops.

This change would solely impact section 9.1, which can be found [here](https://gist.github.com/klardotsh/8f5df312a5af06998e1ba67016846fb9)

>9.1 This Agreement and all disputes, claims, actions, suits or other proceedings arising out of this agreement or relating in any way to it shall be governed by the laws of British Columbia, Canada excluding its private international law provisions.

This would change to

>9.1 This Agreement and all disputes, claims, actions, suits or other proceedings arising out of this agreement or relating in any way to it shall be governed by the laws of the State of Washington, United States of America, excluding its private international law provisions.

General rationale:
- I have no idea how BC software laws work anyway
- I have no idea how long I'll ultimately reside in BC given my immigration status up here literally has "temporary" in the name
- 2/3rds of the members of this Github organization live in Washington, and the last one (myself) is still somewhat of a legal subject of Washington (I'm still a WA resident for voting purposes)
- Changing the CLA after more contributors come on board is going to be way more painful.

Need signoff/comments from all current signers of said CLA, so @kdb424 and @tannewt. If this seems sane and we make the change, we'll also all have to re-click the sign button.

Thanks all!

**Comment by kdb424** [comment]
Sounds reasonable to me

**Comment by tannewt** [comment]
Works for me!

**Comment by klardotsh** [comment]
Updated in the Gist: https://gist.github.com/klardotsh/8f5df312a5af06998e1ba67016846fb9/revisions?short_path=955e991#diff-955e99189b8c80acce923fd3f890f778
