### ISSUE TITLE
BLE on a pico w

### ISSUE THREAD

**Issue by Diggy301** [KMKfw/kmk_firmware#785]
I updated my pico w with the most recent circuit python version and I tried to use BLE with no success.

Has anyone had success with this?

For my implementation I followed the docs http://kmkfw.io/docs/ble_hid#enabling-ble

**Comment by xs5871** [comment]
Circuitpython doesn't support BLE on the pico w. (https://github.com/adafruit/circuitpython/issues/7693)

**Comment by dsz-dsz-k** [comment]
Now that support has been officially added to MicroPython, it would be so nice to have CircuitPython support it too...

**Comment by dsz-dsz-k** [comment]
And apparently, it won't happen any time soon. People over at CircuitPython repository just stated yesterday that updating support for BLE on Pico wasn't a priority...

https://github.com/adafruit/circuitpython/issues/7693#issue-1615701315

**Comment by ItsTerm1n4l** [comment]
Ok, thank you. BLE would be a really good feature for circuit python to implement though. :(
