### ISSUE TITLE
Re-support rotary encoders

### ISSUE THREAD

**Issue by klardotsh** [KMKfw/kmk_firmware#79]
`kmk/rotary_encoder.py` has not been updated to support the new event loop/internals. Fix this, and possibly as part of this work also use `rotaryio` before falling back to our internal implementation.

**Comment by pullenrc** [comment]
I have introduced rotary encoders in a different way, (without using rotaryio, mainly because it wasn't working for me) using an encoder map that will allow the use of velocity for different or combines keys. The files are in my fork, I'm not really sure how to share it other than add it here......

encoder.py
`

import digitalio
      
      
        from .kmktime import ticks_ms
      
      
        

      
      
        #********************** begin single board encoder setup *******************************
      
      
        # # use this for non-split boards, adding more action keys adds more encoders
      
      
        

      
      
        # # The encoders will populate based on several setup lists, all of the list must have the same amount of items
      
      
        # #
      
      
        # keyboard.enable_encoder = True
      
      
        # keyboard.enc_a  =    [board.D40] # list of pad a pins
      
      
        # keyboard.enc_b  =    [board.D41] # list of pad b pins
      
      
        # keyboard.encoder_count = 1 # len(keyboard.enc_a) # number of encoders based off of pad length, or use int
      
      
        

      
      
        # # encoder map follows state layering just like the key map
      
      
        # # the encoder map is a list of lists like the keymap and
      
      
        # # contains 3 item tuples in the format of (increment key, decrement key, resolution).
      
      
        # # the encoder map should have the same amount of layers as the keymap, use noop codes when you want
      
      
        # # to silence the encoder. The amount of tuples should match the number of physical encoders present
      
      
        # keyboard.encoder_map = [
      
      
        #     [
      
      
        #         (KC.VOLU,KC.VOLD,2),# Only 1 encoder is being used, so only one tuple per layer is required
      
      
        #     ],
      
      
        #     [
      
      
        #         (Zoom_in, Zoom_out,1),
      
      
        #     ],
      
      
        #     [
      
      
        #         (_______,_______,1), # no action taken by the encoder on this layer
      
      
        #     ]
      
      
        # ]
      
      
        

      
      
        # # initiate the encoder list
      
      
        # keyboard.make_encoders()
      
      
        # #********************** end single board encoder setup *********************************
      
      
        

      
      
        class Encoder:
      
      
            def __init__(
      
      
                self,
      
      
                pad_a,
      
      
                pad_b,
      
      
                button_pin=None,
      
      
                is_inverted=False,
      
      
                increment_key=None,
      
      
                decrement_key=None,
      
      
                vel_mode=False,
      
      
                use_map = False
      
      
            ):
      
      
                self.pad_a = self.PreparePin(pad_a)  # board pin for enc pin a
      
      
                self.pad_b = self.PreparePin(pad_b)  # board pin for enc pin b
      
      
                self.button_pin = self.PreparePin(button_pin)  # board pin for enc btn
      
      
                self.button_state = None  # state of pushbutton on encoder if enabled
      
      
                self.encoder_value = 0   # clarify what this value is
      
      
                self.encoder_state = "00"  # quaderature encoder state
      
      
                self.encoder_direction = None  # arbitrary, tells direction of knob
      
      
                self.last_encoder_state = None  # not used yet
      
      
                self.resolution = 2  # number of keys sent per position change
      
      
                self.revolution_count = 20  # position changes per revolution
      
      
                self.has_button = False  # enable/disable button functionality
      
      
                self.encoder_data = None  # 6tuple containing all encoder data
      
      
                self.position_change = None  # revolution count, inc/dec as knob turns
      
      
                self.last_encoder_value = 0  # not used
      
      
                self.is_inverted = is_inverted  # switch to invert knob direction
      
      
                self.increment_key = increment_key  # list of increment keys
      
      
                self.decrement_key = decrement_key  # list of decrement keys
      
      
                self.vel_mode = vel_mode  # enable the velocity ouput
      
      
                self.vel_ts = None  # velocity timestamp
      
      
                self.last_vel_ts = 0  # last velocity timestamp
      
      
                self.debug = False  # do not spew debug info by default
      
      
                self.encoder_speed = None  # ms per position change(4 states)
      
      
                self.use_map = use_map
      
      
        

      
      
            # adapted for CircuitPython from raspi
      
      
            def PreparePin(self, num):
      
      
                if num is not None:
      
      
                    pad = digitalio.DigitalInOut(num)
      
      
                    pad.direction = digitalio.Direction.INPUT
      
      
                    pad.pull = digitalio.Pull.UP
      
      
                    return pad
      
      
                else:
      
      
                    return None
      
      
        

      
      
            # checks encoder pins, reports encoder data
      
      
            def report(self):
      
      
                encoder_pad_a = int(self.pad_a.value)
      
      
                encoder_pad_b = int(self.pad_b.value)
      
      
                new_encoder_state = "{}{}".format(encoder_pad_a, encoder_pad_b)
      
      
        

      
      
                if self.encoder_state == "11":  # Resting position
      
      
                    if new_encoder_state == "10":  # Turned right 1
      
      
                        self.encoder_direction = "R"
      
      
                    elif new_encoder_state == "01":  # Turned left 1
      
      
                        self.encoder_direction = "L"
      
      
                elif self.encoder_state == "10":  # R1 or L3 position
      
      
                    if new_encoder_state == "00":  # Turned right 1
      
      
                        self.encoder_direction = "R"
      
      
                    elif new_encoder_state == "11":  # Turned left 1
      
      
                        if self.encoder_direction == "L":
      
      
                            self.encoder_value = self.encoder_value - 1
      
      
                elif self.encoder_state == "01":  # R3 or L1
      
      
                    if new_encoder_state == "00":  # Turned left 1
      
      
                        self.encoder_direction = "L"
      
      
                    elif new_encoder_state == "11":  # Turned right 1
      
      
                        if self.encoder_direction == "R":
      
      
                            self.encoder_value = self.encoder_value + 1
      
      
                else:  # self.encoder_state == '11'
      
      
                    if new_encoder_state == "10":  # Turned left 1
      
      
                        self.encoder_direction = "L"
      
      
                    elif new_encoder_state == "01":  # Turned right 1
      
      
                        self.encoder_direction = "R"
      
      
                    elif (
      
      
                        new_encoder_state == "11"
      
      
                    ):  # Skipped intermediate 01 or 10 state, however turn completed
      
      
                        if self.encoder_direction == "L":
      
      
                            self.encoder_value = self.encoder_value - 1
      
      
                        elif self.encoder_direction == "R":
      
      
                            self.encoder_value = self.encoder_value + 1
      
      
        

      
      
                self.encoder_state = new_encoder_state
      
      
        

      
      
                if self.vel_mode:
      
      
                    self.vel_ts = ticks_ms()
      
      
        

      
      
        

      
      
                if self.encoder_state != self.last_encoder_state:
      
      
                    self.position_change = self.invert_rotation(
      
      
                        self.encoder_value, self.last_encoder_value
      
      
                    )
      
      
        

      
      
                    self.encoder_data = (
      
      
                        self.encoder_state,
      
      
                        self.encoder_direction,
      
      
                        self.encoder_value,
      
      
                        self.position_change,
      
      
                        self.encoder_speed,
      
      
                        self.button_state
      
      
                    )
      
      
                    if self.debug:
      
      
                        print(
      
      
                            'State: {}, \
      
      
                            Direction: {}, \
      
      
                            Value: {}, \
      
      
                            Rev Count: {}, \
      
      
                            Speed: {}" \
      
      
                            Button State: {}'.format(
      
      
                                self.encoder_data[0],
      
      
                                self.encoder_data[1],
      
      
                                self.encoder_data[2],
      
      
                                self.encoder_data[3],
      
      
                                self.encoder_data[4],
      
      
                                self.encoder_data[5]
      
      
                            )
      
      
                        )
      
      
                    self.last_encoder_state = self.encoder_state
      
      
                    self.last_encoder_value = self.encoder_value
      
      
        

      
      
                    if self.position_change &gt; 0:
      
      
                        #return self.increment_key
      
      
                        return 0
      
      
                    elif self.position_change &lt; 0:
      
      
                        #return self.decrement_key
      
      
                        return 1
      
      
                    else:
      
      
                        return None
      
      
        

      
      
            # invert knob direction if encoder pins are soldered backwards
      
      
            def invert_rotation(self, new, old):
      
      
                if self.is_inverted:
      
      
                    return -(new - old)
      
      
                else:
      
      
                    return new - old
      
      
        

      
      
            # returns knob velocity as milliseconds between position changes(detents)
      
      
            def vel_report(self):
      
      
                self.encoder_speed = self.vel_ts - self.last_vel_ts
      
      
                self.last_vel_ts = self.vel_ts
      
      
                <span class="pl-k">return</span> <span class="pl-s1">self</span>.<span class="pl-s1">encoder_speed</span>

`
keyboard.py
`

# There's a chance doing preload RAM hacks this late will cause recursion
      
      
        # errors, but we'll see. I'd rather do it here than require everyone copy-paste
      
      
        # a line into their keymaps.
      
      
        import kmk.preload_imports  # isort:skip # NOQA
      
      
        from kmk import led, rgb
      
      
        import busio
      
      
        from kmk.consts import LeaderMode, UnicodeMode
      
      
        from kmk.hid import AbstractHID, HIDModes
      
      
        from kmk.internal_state import InternalState
      
      
        from kmk.keys import KC
      
      
        from kmk.kmktime import sleep_ms
      
      
        from kmk.matrix import MatrixScanner
      
      
        from kmk.matrix import intify_coordinate as ic
      
      
        from kmk.encoder import Encoder
      
      
        from kmk.graphics import Graphics as Icon
      
      
        import adafruit_ssd1306
      
      
        #import usb_hid
      
      
        #from adafruit_hid.consumer_control import ConsumerControl
      
      
        #from adafruit_hid.consumer_control_code import ConsumerControlCode
      
      
        

      
      
        

      
      
        

      
      
        class KMKKeyboard:
      
      
            debug_enabled = False
      
      
        

      
      
            keymap = None
      
      
            coord_mapping = None
      
      
        

      
      
            row_pins = None
      
      
            col_pins = None
      
      
            diode_orientation = None
      
      
            matrix_scanner = MatrixScanner
      
      
            uart_buffer = []
      
      
        

      
      
            unicode_mode = UnicodeMode.NOOP
      
      
            tap_time = 300
      
      
            leader_mode = LeaderMode.TIMEOUT
      
      
            leader_dictionary = {}
      
      
            leader_timeout = 1000
      
      
        

      
      
            # Split config
      
      
            extra_data_pin = None
      
      
            split_offsets = ()
      
      
            split_flip = False
      
      
            target_side = None
      
      
            split_type = None
      
      
            split_target_left = True
      
      
            is_target = None
      
      
            uart = None
      
      
            uart_flip = True
      
      
            uart_pin = None
      
      
        

      
      
            # RGB config
      
      
            rgb_pixel_pin = None
      
      
            rgb_config = rgb.rgb_config
      
      
        

      
      
            # led config (mono color)
      
      
            led_pin = None
      
      
            led_config = led.led_config
      
      
        

      
      
            # encoder setup
      
      
            enable_encoder = False
      
      
            enc_a = None
      
      
            enc_b = None
      
      
            encoder = []
      
      
            encoder_resolution = None
      
      
            increment_keys = None
      
      
            decrement_keys = None
      
      
            encoder_count = None
      
      
            encoder_map = None
      
      
            use_encoder_map = False
      
      
        

      
      
            # OLED Setup - i2c SSD1306 only at the moment 2 oleds supported
      
      
            i2c_bus0 = None
      
      
            i2c_bus1 = None
      
      
            oleds = []
      
      
            oled_sda = None
      
      
            oled_scl = None
      
      
            oled_height = None
      
      
            oled_width = None
      
      
            oled_bus = None
      
      
            oled_count = None
      
      
            oled_addr = [0x31,0x32]
      
      
            enable_oleds = False
      
      
        

      
      
            graphics = None
      
      
        

      
      
            # mode badge handling
      
      
            prev = None
      
      
            icon = None
      
      
        

      
      
        

      
      
            def __repr__(self):
      
      
                return (
      
      
                    'KMKKeyboard('
      
      
                    'debug_enabled={} '
      
      
                    'keymap=truncated '
      
      
                    'coord_mapping=truncated '
      
      
                    'row_pins=truncated '
      
      
                    'col_pins=truncated '
      
      
                    'diode_orientation={} '
      
      
                    'matrix_scanner={} '
      
      
                    'unicode_mode={} '
      
      
                    'tap_time={} '
      
      
                    'leader_mode={} '
      
      
                    'leader_dictionary=truncated '
      
      
                    'leader_timeout={} '
      
      
                    'hid_helper={} '
      
      
                    'extra_data_pin={} '
      
      
                    'split_offsets={} '
      
      
                    'split_flip={} '
      
      
                    'target_side={} '
      
      
                    'split_type={} '
      
      
                    'split_target_left={} '
      
      
                    'is_target={} '
      
      
                    'uart={} '
      
      
                    'uart_flip={} '
      
      
                    'uart_pin={}'
      
      
                    'enable_encoder={}'
      
      
                    'enc_a={}'
      
      
                    'enc_b={}'
      
      
                    'encoder={}'
      
      
                    'encoder_resolution={}'
      
      
                    'increment_keys={}'
      
      
                    'decrement_keys={}'
      
      
                    'encoder_count={}'
      
      
                    'i2c_bus0={}'
      
      
                    'i2c_buz1={}'
      
      
                    'oleds={}'
      
      
                    'oled_sda={}'
      
      
                    'oled_scl={}'
      
      
                    'oled_height={}'
      
      
                    'oled_width={}'
      
      
                    'oled_bus={}'
      
      
                    'oled_count'
      
      
                    'oled_addr={}'
      
      
                    ')'
      
      
                ).format(
      
      
                    self.debug_enabled,
      
      
                    # self.keymap,
      
      
                    # self.coord_mapping,
      
      
                    # self.row_pins,
      
      
                    # self.col_pins,
      
      
                    self.diode_orientation,
      
      
                    self.matrix_scanner,
      
      
                    self.unicode_mode,
      
      
                    self.tap_time,
      
      
                    self.leader_mode,
      
      
                    # self.leader_dictionary,
      
      
                    self.leader_timeout,
      
      
                    self.hid_helper.__name__,
      
      
                    self.extra_data_pin,
      
      
                    self.split_offsets,
      
      
                    self.split_flip,
      
      
                    self.target_side,
      
      
                    self.split_type,
      
      
                    self.split_target_left,
      
      
                    self.is_target,
      
      
                    self.uart,
      
      
                    self.uart_flip,
      
      
                    self.uart_pin,
      
      
                    self.enable_encoder,
      
      
                    self.enc_a,
      
      
                    self.enc_b,
      
      
                    self.encoder,
      
      
                    self.encoder_resolution,
      
      
                    self.increment_keys,
      
      
                    self.decrement_keys,
      
      
                    self.encoder_count,
      
      
                    self.i2c_bus0,
      
      
                    self.i2c_bus1,
      
      
                    self.oleds,
      
      
                    self.oled_sda,
      
      
                    self.oled_scl,
      
      
                    self.oled_height,
      
      
                    self.oled_width,
      
      
                    self.oled_bus,
      
      
                    self.oled_count,
      
      
                    self.oled_addr
      
      
                )
      
      
        

      
      
        

      
      
            def draw_mode(self, oled, icon):
      
      
                self.clear_oled(oled)
      
      
                for i in icon:
      
      
                    oled.pixel(i[0],i[1],1)
      
      
                oled.show()
      
      
        

      
      
            def make_oleds(self):
      
      
                self.i2c_bus0 = busio.I2C(self.oled_scl[0], self.oled_sda[0])
      
      
                for i in range(self.oled_count):
      
      
                    self.oleds.append(
      
      
                        adafruit_ssd1306.SSD1306_I2C(
      
      
                            self.oled_width[i],
      
      
                            self.oled_height[i],
      
      
                            self.i2c_bus0
      
      
                            )
      
      
                        )
      
      
        

      
      
            def clear_oled(self, oled):
      
      
                # start with a blank screen
      
      
                oled.fill(0)
      
      
                # we just blanked the framebuffer.
      
      
                # to push the framebuffer onto the display, we call show()
      
      
                oled.show()
      
      
        

      
      
            def make_encoders(self):
      
      
                for i in range(self.encoder_count):
      
      
                    self.encoder.append(
      
      
                            Encoder(
      
      
                            self.enc_a[i],  # encoder pin a
      
      
                            self.enc_b[i],  # encoder pin b
      
      
                            None,  # button pin, defaults to None
      
      
                            True,  # invert increment/decrement - defaults to False
      
      
                            #self.increment_keys[i],  # keycode for increment
      
      
                            #self.decrement_keys[i],  # keycode for decrement
      
      
                            vel_mode = False # use velocity mode
      
      
                            )
      
      
                        )
      
      
        

      
      
            def _send_hid(self):
      
      
                self._hid_helper_inst.create_report(self._state.keys_pressed).send()
      
      
                self._state.resolve_hid()
      
      
        

      
      
            def _send_key(self, key):
      
      
                if not getattr(key, 'no_press', None):
      
      
                    self._state.add_key(key)
      
      
                    self._send_hid()
      
      
        

      
      
                if not getattr(key, 'no_release', None):
      
      
                    self._state.remove_key(key)
      
      
                    self._send_hid()
      
      
        

      
      
            def _handle_matrix_report(self, update=None):
      
      
                '''
      
      
                Bulk processing of update code for each cycle
      
      
                :param update:
      
      
                '''
      
      
                if update is not None:
      
      
        

      
      
                    self._state.matrix_changed(update[0], update[1], update[2])
      
      
        

      
      
            def _send_to_target(self, update):
      
      
                if self.split_target_left:
      
      
                    update[1] += self.split_offsets[update[0]]
      
      
                else:
      
      
                    update[1] -= self.split_offsets[update[0]]
      
      
                if self.uart is not None:
      
      
                    self.uart.write(update)
      
      
        

      
      
            def _receive_from_initiator(self):
      
      
                if self.uart is not None and self.uart.in_waiting &gt; 0 or self.uart_buffer:
      
      
                    if self.uart.in_waiting &gt;= 60:
      
      
                        # This is a dirty hack to prevent crashes in unrealistic cases
      
      
                        import microcontroller
      
      
        

      
      
                        microcontroller.reset()
      
      
        

      
      
                    while self.uart.in_waiting &gt;= 3:
      
      
                        self.uart_buffer.append(self.uart.read(3))
      
      
                    if self.uart_buffer:
      
      
                        update = bytearray(self.uart_buffer.pop(0))
      
      
        

      
      
                        # Built in debug mode switch
      
      
                        if update == b'DEB':
      
      
                            print(self.uart.readline())
      
      
                            return None
      
      
                        return update
      
      
        

      
      
                return None
      
      
        

      
      
            def _send_debug(self, message):
      
      
                '''
      
      
                Prepends DEB and appends a newline to allow debug messages to
      
      
                be detected and handled differently than typical keypresses.
      
      
                :param message: Debug message
      
      
                '''
      
      
                if self.uart is not None:
      
      
                    self.uart.write('DEB')
      
      
                    self.uart.write(message, '\n')
      
      
        

      
      
            def init_uart(self, pin, timeout=20):
      
      
                if self.is_target:
      
      
                    return busio.UART(tx=None, rx=pin, timeout=timeout)
      
      
                else:
      
      
                    return busio.UART(tx=pin, rx=None, timeout=timeout)
      
      
        

      
      
            def send_encoder_keys(self, encoder_key, encoder_idx):
      
      
                encoder_resolution = 2
      
      
                for _ in range(self.encoder_map[self._state.active_layers[0]][encoder_idx][encoder_resolution]):
      
      
                    #self._send_key(encoder_key)
      
      
                    self._send_key(self.encoder_map[self._state.active_layers[0]][encoder_idx][encoder_key])
      
      
        

      
      
            def go(self, hid_type=HIDModes.USB, **kwargs):
      
      
                assert self.keymap, 'must define a keymap with at least one row'
      
      
                assert self.row_pins, 'no GPIO pins defined for matrix rows'
      
      
                assert self.col_pins, 'no GPIO pins defined for matrix columns'
      
      
                assert self.diode_orientation is not None, 'diode orientation must be defined'
      
      
                assert (
      
      
                    hid_type in HIDModes.ALL_MODES
      
      
                ), 'hid_type must be a value from kmk.consts.HIDModes'
      
      
        

      
      
                # Attempt to sanely guess a coord_mapping if one is not provided
      
      
        

      
      
                if not self.coord_mapping:
      
      
                    self.coord_mapping = []
      
      
        

      
      
                    rows_to_calc = len(self.row_pins)
      
      
                    cols_to_calc = len(self.col_pins)
      
      
        

      
      
                    if self.split_offsets:
      
      
                        rows_to_calc *= 2
      
      
                        cols_to_calc *= 2
      
      
        

      
      
                    for ridx in range(rows_to_calc):
      
      
                        for cidx in range(cols_to_calc):
      
      
                            self.coord_mapping.append(ic(ridx, cidx))
      
      
                self.icon = Icon()
      
      
                self._state = InternalState(self)
      
      
                if hid_type == HIDModes.NOOP:
      
      
                    self.hid_helper = AbstractHID
      
      
                elif hid_type == HIDModes.USB:
      
      
                    try:
      
      
                        from kmk.hid import USBHID
      
      
        

      
      
                        self.hid_helper = USBHID
      
      
                    except ImportError:
      
      
                        self.hid_helper = AbstractHID
      
      
                        print('USB HID is unsupported ')
      
      
                elif hid_type == HIDModes.BLE:
      
      
                    try:
      
      
                        from kmk.ble import BLEHID
      
      
        

      
      
                        self.hid_helper = BLEHID
      
      
                    except ImportError:
      
      
                        self.hid_helper = AbstractHID
      
      
                        print('Bluetooth is unsupported ')
      
      
        

      
      
                self._hid_helper_inst = self.hid_helper(**kwargs)
      
      
        

      
      
                # Split keyboard Init
      
      
                if self.split_type is not None:
      
      
                    try:
      
      
                        # Working around https://github.com/adafruit/circuitpython/issues/1769
      
      
                        self._hid_helper_inst.create_report([]).send()
      
      
                        self.is_target = True
      
      
        

      
      
                        # Sleep 2s so target portion doesn't "appear" to boot quicker than
      
      
                        # dependent portions (which will take ~2s to time out on the HID send)
      
      
                        sleep_ms(2000)
      
      
                    except OSError:
      
      
                        self.is_target = False
      
      
        

      
      
                    if self.split_flip and not self.is_target:
      
      
                        self.col_pins = list(reversed(self.col_pins))
      
      
                    if self.target_side == 'Left':
      
      
                        self.split_target_left = self.is_target
      
      
                    elif self.target_side == 'Right':
      
      
                        self.split_target_left = not self.is_target
      
      
                else:
      
      
                    self.is_target = True
      
      
        

      
      
                if self.uart_pin is not None:
      
      
                    self.uart = self.init_uart(self.uart_pin)
      
      
        

      
      
                if self.rgb_pixel_pin:
      
      
                    self.pixels = rgb.RGB(self.rgb_config, self.rgb_pixel_pin)
      
      
                    self.rgb_config = None  # No longer needed
      
      
                    self.pixels.loopcounter = 0
      
      
                else:
      
      
                    self.pixels = None
      
      
        

      
      
                if self.led_pin:
      
      
                    self.led = led.led(self.led_pin, self.led_config)
      
      
                    self.led_config = None  # No longer needed
      
      
                else:
      
      
                    self.led = None
      
      
        

      
      
                self.matrix = self.matrix_scanner(
      
      
                    cols=self.col_pins,
      
      
                    rows=self.row_pins,
      
      
                    diode_orientation=self.diode_orientation,
      
      
                    rollover_cols_every_rows=getattr(self, 'rollover_cols_every_rows', None),
      
      
                )
      
      
        

      
      
                # Compile string leader sequences
      
      
                for k, v in self.leader_dictionary.items():
      
      
                    if not isinstance(k, tuple):
      
      
                        new_key = tuple(KC[c] for c in k)
      
      
                        self.leader_dictionary[new_key] = v
      
      
        

      
      
                for k, v in self.leader_dictionary.items():
      
      
                    if not isinstance(k, tuple):
      
      
                        del self.leader_dictionary[k]
      
      
        

      
      
                if self.oleds != None:
      
      
                    self.clear_oled(self.oleds[0])
      
      
        

      
      
                if self.enable_oleds:
      
      
                    self.draw_mode(self.oleds[0], self.icon.mode_icons[0][1])
      
      
        

      
      
                while True:
      
      
                    if self.split_type is not None and self.is_target:
      
      
                        update = self._receive_from_initiator()
      
      
                        if update is not None:
      
      
                            self._handle_matrix_report(update)
      
      
        

      
      
        

      
      
                    update = self.matrix.scan_for_changes()
      
      
        

      
      
                    if update is not None:
      
      
                        #print(self._state.active_layers)
      
      
                        if self.is_target:
      
      
                            self._handle_matrix_report(update)
      
      
                        else:
      
      
                            # This keyboard is a initiator, and needs to send data to target
      
      
                            self._send_to_target(update)
      
      
        

      
      
                    if self.enable_oleds:
      
      
                        if self._state.active_layers[0] != self.prev:
      
      
                            #self.clear_oled(self.oleds[0])
      
      
                            self.draw_mode(
      
      
                                self.oleds[0],
      
      
                                self.icon.mode_icons[self._state.active_layers[0]][1]
      
      
                                )
      
      
                            self.prev = self._state.active_layers[0]
      
      
        

      
      
                    if self.enable_encoder:
      
      
                        for idx in range(self.encoder_count):
      
      
                            encoder_key = self.encoder[idx].report()
      
      
                            if encoder_key is not None:
      
      
                                self.send_encoder_keys(encoder_key,idx)
      
      
        

      
      
                    if self._state.hid_pending:
      
      
                        self._send_hid()
      
      
        

      
      
                    old_timeouts_len = len(self._state.timeouts)
      
      
                    self._state.process_timeouts()
      
      
                    new_timeouts_len = len(self._state.timeouts)
      
      
        

      
      
                    if old_timeouts_len != new_timeouts_len:
      
      
                        if self._state.hid_pending:
      
      
                            self._send_hid()
      
      
        

      
      
                    if self.pixels and self.pixels.animation_mode:
      
      
                        self.pixels.loopcounter += 1
      
      
                        if self.pixels.loopcounter &gt;= 30:
      
      
                            self.pixels = self.pixels.animate()
      
      
                            self.pixels.loopcounter = 0
      
      
        

      
      
                    if self.led and self.led.enabled and self.led.animation_mode:
      
      
                        <span class="pl-s1">self</span>.<span class="pl-s1">led</span> <span class="pl-c1">=</span> <span class="pl-s1">self</span>.<span class="pl-s1">led</span>.<span class="pl-en">animate</span>()

`
keymap
`import gc

from kmk.boards.teensy_41.pytreus import KMKKeyboard
from kmk.consts import LeaderMode, UnicodeMode
from kmk.handlers.sequences import compile_unicode_string_sequences as cuss
from kmk.handlers.sequences import send_string
from kmk.keys import KC, make_key

from kmk.consts import KMK_RELEASE
print(KMK_RELEASE)

import board



local_increment = None
local_decrement = None

keyboard = KMKKeyboard()
keyboard.tap_time = 250
keyboard.debug_enabled = False

# custom keys used for encoder actions
Zoom_in = KC.LCTRL(KC.EQUAL)
Zoom_out = KC.LCTRL(KC.MINUS)

# standard filler keys
_______ = KC.TRNS
XXXXXXX = KC.NO
CAD = KC.LCTL(KC.LALT(KC.DEL))
RES = KC.LCTL(KC.LSFT(KC.ESC))
FE = KC.LGUI(KC.E)
LT1_DEL = KC.LT(1,KC.DEL)
LT2_ENT = KC.LT(2, KC.ENT)

# programming layer keys
INT = send_string('int')
UINT = send_string('uint')
DOUBLE = send_string('double') 
BOOL = send_string('bool')
BYTE = send_string('byte') 
SBYTE = send_string('sbyte')
CHAR = send_string('char')
GETSET = send_string('{get; set; }')
PUBLIC = send_string('public ')

# tapdance config
#MODE_TD = KC.TD(
    #KC.MO(1),
    #KC.MO(2),
#)

PRINT = send_string('print(')
DEBUGWL = send_string('Debug.WriteLine(')


#### begin oled config ####
keyboard.enable_oleds = True
keyboard.oled_scl = [board.SCL]
keyboard.oled_sda = [board.SDA]
keyboard.oled_width = [128]
keyboard.oled_height = [32]
keyboard.oled_count = len(keyboard.oled_width)
keyboard.make_oleds()
#### end oled config ####


#********************** begin single board encoder setup *******************************
# use this for non-split boards, adding more action keys adds more encoders

# The encoders will populate based on several setup lists, all of the list must have the same amount of items
#
keyboard.enable_encoder = True
keyboard.enc_a  =    [board.D40] # list of pad a pins
keyboard.enc_b  =    [board.D41] # list of pad b pins
keyboard.encoder_count = 1 # len(keyboard.enc_a) # number of encoders based off of pad length, or use int

# encoder map follows state layering just like the key map
# the encoder map is a list of lists like the keymap and
# contains 3 item tuples in the format of (increment key, decrement key, resolution).
# the encoder map should have the same amount of layers as the keymap, usenoop codes when you want
# to sicence the encoder. The amount of tuples should match the number of physical encoders present
keyboard.encoder_map = [
    [
        (KC.VOLU,KC.VOLD,2),# Only 1 encoder is being used, so only one tuple per layer is required
    ],
    [
        (Zoom_in, Zoom_out,1),
    ],
    [
        (_______,_______,1), # no action taken by the encoder on this layer
    ]
]

# initiate the encoder list
keyboard.make_encoders()
#********************** end single board encoder setup *********************************



# below is the deprecated encoder constructor, left here as notes for now.
# #********************** begin split board encoder setup ********************************
# # handle keycode setup for split boards using the same MCU pins for encoders
# # use this only for split keyboards
# keyboard.enable_encoder = True
# if keyboard.is_target:
#     local_increment = [KC.VOLU]
#     local_decrement = [KC.VOLD]
# elif not keyboard.is_target:
#     local_increment = [Zoom_in]
#     local_decrement = [Zoom_out]


# # begin encoder birthing
# keyboard.enc_a = [board.D31] # list of pad a pins
# keyboard.enc_b = [board.D32] # list of pad b pins
# keyboard.encoder_resolution = [4] # list of encoder resolutions
# keyboard.increment_keys = local_increment # list of increment key codes
# keyboard.decrement_keys = local_decrement # list of decrement key codes
# keyboard.encoder_count = len(keyboard.enc_a) # number of encoders based off of pad length
# # initiate the encoder list
# keyboard.make_encoders()
# #********************** end split board encoder setup **********************************


# make keymap
keyboard.keymap = [
    [
        KC.ESC,   KC.N1,   KC.N2,   KC.N3,   KC.N4,   KC.N5,       KC.N6,     KC.N7,   KC.N8,   KC.N9,   KC.N0,   KC.MINS,
        CAD,      KC.Q,    KC.W,    KC.E,    KC.R,    KC.T,        KC.Y,      KC.U,    KC.I,    KC.O,    KC.P,    KC.BSLS,
        KC.TAB,   KC.A,    KC.S,    KC.D,    KC.F,    KC.G,        KC.H,      KC.J,    KC.K,    KC.L,    KC.SCLN, KC.QUOT,
        KC.LSFT,  KC.Z,    KC.X,    KC.C,    KC.V,    KC.B,        KC.N,      KC.M,    KC.COMM, KC.DOT,  KC.SLSH,  FE,
        KC.BSPC,  KC.DEL, KC.LALT, KC.LSFT, KC.LCTL,  KC.BSPC,     KC.SPC,    KC.ENT,  KC.LSFT, KC.RCTL, KC.ENT,  KC.RGUI,
        XXXXXXX,  XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, KC.MO(1),    KC.MO(2),  KC.MUTE, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
    ],
    [
        RES,      XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,     KC.PSLS, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, KC.MINS,
        KC.BSLS,  XXXXXXX, XXXXXXX, KC.UP,   XXXXXXX, XXXXXXX,     KC.PAST, KC.N7,   KC.N8,   KC.N9,   XXXXXXX, KC.BSLS,
        KC.TAB,   XXXXXXX, KC.LEFT, KC.DOWN, KC.RIGHT,KC.HASH,     KC.PPLS, KC.N4,   KC.N5,   KC.N6,   XXXXXXX, KC.QUOT,
        KC.LSFT,  XXXXXXX, XXXXXXX, KC.C,    KC.TAB,  KC.UNDS,     KC.MINS, KC.N1,   KC.N2,   KC.N3,   XXXXXXX, KC.LBRC,
        KC.BSPC,  XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, _______,     KC.SPC,  KC.EQUAL,  KC.N0, KC.RALT, KC.ENT,  KC.RGUI,
        XXXXXXX,  XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, _______,     _______, _______,   XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
    ],
    [
        RES,      KC.N1,   KC.N2,   KC.N3,   KC.N4,      KC.N5,      DEBUGWL,    PRINT,   KC.N8,   KC.N9,   KC.N0,   KC.MINS,
        KC.BSLS,  KC.Q,    KC.W,    KC.LCBR, KC.RCBR,    KC.AT,      INT,     PUBLIC,    GETSET,    KC.O,    KC.P,    KC.BSLS,
        KC.TAB,   KC.A,    KC.S,    KC.LPRN, KC.RPRN,    KC.DLR,     BOOL,     DOUBLE,    KC.K,    KC.L,    KC.SCLN, KC.QUOT,
        KC.LSFT,  KC.Z,    KC.X,    KC.LBRC, KC.RBRC,    KC.PERC,    UINT ,     BYTE,    KC.COMM, KC.DOT,  KC.SLSH, KC.LBRC,
        KC.BSPC,  KC.LGUI, KC.LALT, KC.LSFT, KC.LCTL,    KC.DEL,     _______,  KC.EQL,  KC.RCTL, KC.RALT, KC.ENT,  KC.RGUI,
        XXXXXXX,  XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,   _______,     _______, _______,  XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
    ]
]


if __name__ == "__main__":
    keyboard.go()
`

**Comment by klardotsh** [comment]
Sharing your contributions upstream would just be a pull request in Github: https://github.com/pullenrc/kmk_firmware/pull/new/master

I haven't actually grokked all of what's happening here but I'll say in the abstract I would _love_ to work with you (and anyone else interested) to get a working rotary encoder implementation in - preferably rebased on `topic-keyboard-and-state-rebased`, but regardless. We get a lot of requests for this functionality in Matrix (@kdb424 can confirm, he handles a lot more of that room than I do) and it'd be awesome to have a "canonical" way.

**Comment by pullenrc** [comment]
Awesome, I am just going to clean some things up and I send a pull request.
