### ISSUE TITLE
[BUG] Split keyboard EE docs misguiding

### ISSUE THREAD

**Issue by larryare** [KMKfw/kmk_firmware#808]
**Describe the bug**
As per split keyboard docs, in EE section, it's noted that only this is enough:
```
# Wired
split = Split()
```
However i get the error:  `kmk.modules.split: during_bootup: AttributeError: 'KMKKeyboard' object has no attribute 'data_pin'`. My UART pins are wired to default GP0 and GP1. I'm using two raspberry pi picos.

**Expected behavior**
Docs should mention, at least at the EE section, that providing UART pins are required arguments.

**Comment by xs5871** [comment]
Good point.
