### ISSUE TITLE
[Enhancement] Generate mpy artifacts only on changed source

### ISSUE THREAD

**Issue by xs5871** [KMKfw/kmk_firmware#818]
**Is your feature request related to a problem? Please describe.**
We started building mpy artifacts to download for every PR merge. Those builds are also triggered for documentation or board code updates.

**Describe the solution you'd like**
Look into using [a changed files GH action](https://github.com/tj-actions/changed-files) (see #800) to generate mpy artifacts only when the python source tree has changed.

**Comment by rrotter** [comment]
Looks like this is the solution:

https://stackoverflow.com/questions/70902669/github-action-trigger-a-job-only-when-there-is-a-change-in-particular-director

**Comment by xs5871** [comment]
Thanks for the reminder. We actually have a pending PR #857 that does that (well not yet, hence pending).
