### ISSUE TITLE
Works fine in windows, writes giberrish in linux

### ISSUE THREAD

**Issue by Jambul46** [KMKfw/kmk_firmware#844]
When typing in windows everythings fine, no delay, no laggynes nothing but when i use linux i sometimes have to press the key at least 3 times to write one character and sometimes i press it once and it's like iam holding it. It also likes to disconnect from the pc.

CODE: https://pastebin.com/CF4zzb75

Sry for my english.

**Comment by xs5871** [comment]
Doesn't sound like KMK is the issue. Disable usb storage and see if that helps.

**Comment by Jambul46** [comment]
Might have found the issue... unpowered usb hub i'll try directly conmecting it.

**Comment by Jambul46** [comment]
Yep it was the unpowered hub. Sry i didn't try that before opening this issue.
