### ISSUE TITLE
[Enhancement] Stable Release Version

### ISSUE THREAD

**Issue by syenasweta** [KMKfw/kmk_firmware#866]
Hi, all.

I have a suggestion that KMK Firmware has a release version on Github. It will be better than end user downloading production version of KMK Firmware via https://github.com/KMKfw/kmk_firmware/archive/refs/heads/master.zip. KMK Firmware can specify a stable release version for end users to use. Meanwhile, the production version may be updated at any time.

**Comment by xs5871** [comment]
That pretty much covers it. KMK is live at head, which means whatever is the most recent code is also the most stable.
Versioning does not reflect the way current maintenance and development is done in KMK, and it would not only be overhead, but also non-sensical.
