### ISSUE TITLE
Add backspace/Delete key combo

### ISSUE THREAD

**Issue by kdb424** [KMKfw/kmk_firmware#93]
Through MOD4, similar to GESC.

**Comment by klardotsh** [comment]
Added milestone to make this a v1 blocker - while I think this is of remarkably limited utility (Mod4+Backspace is needed in some OS/WM-level shortcuts on some systems, and throwing delete on a fn layer is trivial), abstracting out this type of behaviour will actually help solve #106 in a more sane way I think.
