### ISSUE TITLE
[RGB] do anyone made a standard 4pin RGB library?

### ISSUE THREAD

**Issue by cartaio** [KMKfw/kmk_firmware#938]
Hi everyone! i have [this](https://it.aliexpress.com/item/1005004770568680.html?spm=a2g0o.order_list.order_list_main.58.29543696iq7WdU&gatewayAdapt=glo2ita) laying around the lab... do anyone build a library for this? or any RGB strip with 4 pin (R/G/B/+3.3). i just want to add backlight to my DIY macro keyboard.

**Comment by xs5871** [comment]
Those are just 3 LEDs in a single package. They'll work with the `led` extension.

**Comment by xs5871** [comment]
Closing as resolved.
