### ISSUE TITLE
[BUG] Combos with home row modifiers like KC.HT(KC.F, KC.LSFT)

### ISSUE THREAD

**Issue by juru1234** [KMKfw/kmk_firmware#939]
**Describe the bug**
Hi, I want to use combos along with home row modifiers.
When I tap an hold press F, it should be LSFT.
When I tap and hold D, it should be LCTRL.
When I tap F and D as a combo, it should be ESC.

I tried something like this but it does not seem to work:
`Chord((KC.HT(KC.D, KC.LCTRL), KC.HT(KC.F, KC.LSFT)), KC.ESC)`

Is this feature not implemented in KMK?

**Comment by xs5871** [comment]
You have to alias the hold-tap keys and use that alias in the combo and keymap.
Argumented keys are dynamically created; even though two argumented keys (hold-tap in this case) may have the same arguments, they are different objects.

**Comment by juru1234** [comment]
Yeah, it works! Thank you so much!

**Comment by juru1234** [comment]
Yeah, it works! Thank you so much!
