### ISSUE TITLE
The ADNS9800 does not move the mouse smoothly enough in Bluetooth mode

### ISSUE THREAD

**Issue by Felix-12138** [KMKfw/kmk_firmware#964]
When I use the adns9800 trackball module, it is perfect in USB mode, but in BLE mode, there will be frame loss when the mouse moves, how can I solve it? Is the working mode of HIDBLE not fast enough to send and receive data?

**Comment by claycooper** [comment]
Take a look at the bottom of the [Getting Started](https://kmkfw.io/Getting_Started/) guide on how to get help.

I'm going to close this out and a new issue can be filed if it's determined that there's a bug.
